### ISSUE TITLE
Blue Media button icon

### ISSUE THREAD

**Issue by sayam93** [jimmy-landry/HA-Tablet-Dashboard-Config#1]
Hi Jimmy,

Thanks for the tutorial. Great work! I love this theme and have been using it for a few weeks now. I finally decided add some media players but am facing a small issue. The icons are blue when the player isn't in the 
'playing' state.

If you could kindly post the code for the homepod button (button card and not the mini media player) that's visible at [https://youtu.be/d9ewXJsxKrI?t=5](https://www.youtube.com/watch?v=d9ewXJsxKrI&t=5s) since I am not really able to find it anywhere.

Thanks!
Sayam

<img width="382" alt="Screenshot 2024-04-21 at 1 11 07 AM" src="https://github.com/jimmy-landry/HA-Tablet-Dashboard-Config/assets/163408168/d5081a4c-609a-4d7b-812a-557b76d72197">

I am using the below code

```
type: custom:button-card
template: light
entity: media_player.tv
name: Apple TV
icon: phu:apple-tv-box
size: 70%
show_state: false
aspect_ratio: 1/1
tap-action:
  action: none

```

**Comment by jimmy-landry** [comment]
Hi sayam93,

This is the code I use for the HomePod button on my dashboard:
```
type: custom:button-card
template:
  - base
entity: media_player.bedroom_homepod
name: HomePod
icon: phu:homepod-mini
size: 80%
show_state: true
aspect_ratio: 1/1
tap_action:
  action: call-service
  service: media_player.media_play_pause
  data: {}
  target:
    entity_id: media_player.bedroom_homepod
state:
  - value: paused
    styles:
      icon:
        - color: rgb(60, 60, 60)
  - value: playing
    styles:
      icon:
        - color: rgb(64,155,242)
```

You should be able to override the default colors by using the state object built into button card. The HomePods don't have an on/off state, they're either playing or not playing, so that's why I only have playing and paused listed inside the state object. So, if you wanted to change the color of the icon when your Apple TV is off, you would replace "paused" inside the state object with "off." Hopefully that makes sense 😀

That code gets me a gray icon/gray background when the HomePod is paused:

<img width="246" alt="Screenshot 2024-04-27 at 8 55 08 AM" src="https://github.com/jimmy-landry/HA-Tablet-Dashboard-Config/assets/121106900/2f1be7ff-3325-4c6f-aa92-13331954e3fe">

And a blue icon/white background when the HomePod is playing:

<img width="246" alt="Screenshot 2024-04-27 at 8 54 50 AM" src="https://github.com/jimmy-landry/HA-Tablet-Dashboard-Config/assets/121106900/400d6ea8-3527-40de-bb5b-3e0bef90ccf5">
